# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='business_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AddField(
            model_name='resource',
            name='business_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='business_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='location',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='business_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
    ]
