# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20160530_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='service',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='service',
        ),
        migrations.AddField(
            model_name='material',
            name='business_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business'),
        ),
    ]
