# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20160531_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
