# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='standard',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
