# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_auto_20160601_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='school_year',
            field=models.IntegerField(default=0),
        ),
    ]
