# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_goal_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('business_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
            ],
        ),
    ]
