# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_monthlyweatherbycity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('school_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='score',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='goal_score',
            name='goal_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Goal'),
        ),
    ]
