# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0009_auto_20160607_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2015)),
                ('finance_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Finance')),
            ],
        ),
    ]
