# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_finance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('reservation', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='spaces',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.Location'),
        ),
    ]
