# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_auto_20160608_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
