# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_delete_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='used_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
